server:
    port: 8080
    servlet-path: /
spring:
  application:
    name: dead-code-analyzer
  jersey:
    application-path: /api
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
        WRITE_DATES_AS_TIMESTAMPS: false