server:
    port: 8080
    servlet-path: /swagger
spring:
  application:
    name: dead-code-analyzer
  jersey:
    application-path: /
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: NON_ABSENT
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true