/*
 * Swagger Dead Code Analizer YAML
 * This is a simple service to submit you java project to analyse dead code using SciTool.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lahiru.karunatilake@aurea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
