/*
 * Swagger Dead Code Analizer YAML
 * This is a simple service to submit you java project to analyse dead code using SciTool.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lahiru.karunatilake@aurea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FunctionParameter;
import io.swagger.client.model.LocalVariable;
import java.util.ArrayList;
import java.util.List;

/**
 * Function
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-07T07:50:26.541Z")
public class Function {
  @SerializedName("name")
  private String name = null;

  @SerializedName("lineNo")
  private Long lineNo = null;

  @SerializedName("columnNo")
  private Long columnNo = null;

  @SerializedName("parameters")
  private List<FunctionParameter> parameters = new ArrayList<FunctionParameter>();

  @SerializedName("variables")
  private List<LocalVariable> variables = new ArrayList<LocalVariable>();

  public Function name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Function lineNo(Long lineNo) {
    this.lineNo = lineNo;
    return this;
  }

   /**
   * Get lineNo
   * @return lineNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLineNo() {
    return lineNo;
  }

  public void setLineNo(Long lineNo) {
    this.lineNo = lineNo;
  }

  public Function columnNo(Long columnNo) {
    this.columnNo = columnNo;
    return this;
  }

   /**
   * Get columnNo
   * @return columnNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getColumnNo() {
    return columnNo;
  }

  public void setColumnNo(Long columnNo) {
    this.columnNo = columnNo;
  }

  public Function parameters(List<FunctionParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public Function addParametersItem(FunctionParameter parametersItem) {
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FunctionParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<FunctionParameter> parameters) {
    this.parameters = parameters;
  }

  public Function variables(List<LocalVariable> variables) {
    this.variables = variables;
    return this;
  }

  public Function addVariablesItem(LocalVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * Get variables
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<LocalVariable> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Function function = (Function) o;
    return Objects.equals(this.name, function.name) &&
        Objects.equals(this.lineNo, function.lineNo) &&
        Objects.equals(this.columnNo, function.columnNo) &&
        Objects.equals(this.parameters, function.parameters) &&
        Objects.equals(this.variables, function.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, lineNo, columnNo, parameters, variables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Function {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lineNo: ").append(toIndentedString(lineNo)).append("\n");
    sb.append("    columnNo: ").append(toIndentedString(columnNo)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

