/*
 * Swagger Dead Code Analizer YAML
 * This is a simple service to submit you java project to analyse dead code using SciTool.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lahiru.karunatilake@aurea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LocalVariable
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-07T07:50:26.541Z")
public class LocalVariable {
  @SerializedName("name")
  private String name = null;

  @SerializedName("lineNo")
  private Long lineNo = null;

  @SerializedName("columnNo")
  private Long columnNo = null;

  public LocalVariable name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LocalVariable lineNo(Long lineNo) {
    this.lineNo = lineNo;
    return this;
  }

   /**
   * Get lineNo
   * @return lineNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLineNo() {
    return lineNo;
  }

  public void setLineNo(Long lineNo) {
    this.lineNo = lineNo;
  }

  public LocalVariable columnNo(Long columnNo) {
    this.columnNo = columnNo;
    return this;
  }

   /**
   * Get columnNo
   * @return columnNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getColumnNo() {
    return columnNo;
  }

  public void setColumnNo(Long columnNo) {
    this.columnNo = columnNo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalVariable localVariable = (LocalVariable) o;
    return Objects.equals(this.name, localVariable.name) &&
        Objects.equals(this.lineNo, localVariable.lineNo) &&
        Objects.equals(this.columnNo, localVariable.columnNo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, lineNo, columnNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalVariable {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lineNo: ").append(toIndentedString(lineNo)).append("\n");
    sb.append("    columnNo: ").append(toIndentedString(columnNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

